export default[
    { Commune: 'La Chaux-de-Fonds', GWh: 226.46 },
    { Commune: 'Neuchâtel', GWh: 204.92 },        
    { Commune: 'Val-de-Ruz', GWh: 168.73 },       
    { Commune: 'Val-de-Travers', GWh: 135.33 },   
    { Commune: 'Le Locle', GWh: 85.09 },
    { Commune: 'La Grande-Béroche', GWh: 75.55 }, 
    { Commune: 'Milvignes', GWh: 58.69 },
    { Commune: 'La Tène', GWh: 42.36 },
    { Commune: 'Boudry', GWh: 38.72 },
    { Commune: 'Cortaillod', GWh: 35.17 },
    { Commune: 'Le Landeron', GWh: 30.96 },
    { Commune: 'Cressier (NE)', GWh: 24.83 },
    { Commune: 'La Brévine', GWh: 21.89 },
    { Commune: 'Saint-Blaise', GWh: 21.68 },
    { Commune: 'Les Ponts-de-Martel', GWh: 20.75 },
    { Commune: 'Les Verrières', GWh: 18.53 },
    { Commune: 'La Sagne', GWh: 17.58 },
    { Commune: 'Cornaux', GWh: 17.27 },
    { Commune: 'Lignières', GWh: 15.22 },
    { Commune: 'Rochefort', GWh: 15 },
    { Commune: 'Hauterive (NE)', GWh: 12.23 },
    { Commune: 'La Chaux-du-Milieu', GWh: 11.26 },
    { Commune: 'La Côte-aux-Fées', GWh: 11.14 },
    { Commune: 'Brot-Plamboz', GWh: 9.31 },
    { Commune: 'Le Cerneux-Péquignot', GWh: 8.89 },
    { Commune: 'Les Planchettes', GWh: 4.13 },
    { Commune: 'Enges', GWh: 3.76 }
  ]